run_all_in_parallel:
	make clean_it test_parallel

clean_it:
	mvn clean

test_parallel:
	make -j test_chrome test_firefox

test_firefox:
	mvn test -Dbrowser=firefox

test_ie:
	mvn test -Dbrowser=ie

test_safari:
	mvn install -Dbrowser=safari

test_chrome:
	mvn test -Dbrowser=chrome

test_local:
    mvn install -Dbrowser=chrome -Dlocal=true